<a href="https://colab.research.google.com/github/yoosoobin/algorithm_study/blob/master/02_1_numpy%2C_pandas_%EC%B9%9C%ED%95%B4%EC%A7%80%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import numpy as np

리스트, 행렬 선언

In [7]:
# list_name(변수명 설정) = ["item-1", "item-2", ... , "item-n"]

a = [1, 2, 3]
b = ["a", "b", "c"]
c = [["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]]

print(a)
print(b)
print(c)

[1, 2, 3]
['a', 'b', 'c']
[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c']]


In [8]:
a.append('new_items')
c.append(['new'])

In [9]:
print(a)
print(c)

[1, 2, 3, 'new_items']
[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c'], ['new']]


In [10]:
a = np.array([1, 2, 3])
b = np.array(["a", "b", "c"])
c = np.array([["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]])

print(a)
print(b)
print(c)

[1 2 3]
['a' 'b' 'c']
[list(['a']) list(['a', 'b']) list(['a', 'c']) list(['a', 'b', 'c'])]


In [12]:
print(np.ones((1,5))) #행,열
print(np.ones((3,2)))

[[1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
np.zeros((1,5))

array([[0., 0., 0., 0., 0.]])

In [14]:
# 주어진 범위 안에서 순차적으로 증가하는 리스트 만들기
# np.arange([start,] stop, [step, ] dtype=None)

print(np.arange(10))
print(np.arange(3,7, dtype=np.float))
print(np.arange(3,10,2))

[0 1 2 3 4 5 6 7 8 9]
[3. 4. 5. 6.]
[3 5 7 9]


In [15]:
# 행렬 선언하기
mat1 = np.array([[1,2,3],[4,5,6]])

# random으로 matrix 만들기
mat2 = np.random.randint(low=1, high=10, size=(3,2))
mat3 = np.random.rand(3,2) # 정규분포를 가지는 3행2열 사이즈를 만들어라

print(mat1)
print(mat2)
print(mat3)

[[1 2 3]
 [4 5 6]]
[[8 5]
 [6 8]
 [4 3]]
[[0.03398481 0.99792925]
 [0.29388948 0.40098615]
 [0.72674725 0.21716695]]


리스트 인덱싱, 슬라이싱

In [16]:
# Indexing
a = [1,3,5,7,9,11]
print(a[2], a[5], a[-1])

5 11 11


In [17]:
# Slicing
b = [2,4,6,8,10]
print(b[2:])
print(b[:2])
print(b[:])

[6, 8, 10]
[2, 4]
[2, 4, 6, 8, 10]


umpy의 reshape (PyTorch의 view와 비교)

In [18]:
# (row, column)
mat1 = np.random.rand(6,3)
print(mat1)

[[0.29649438 0.14200824 0.31950093]
 [0.50969565 0.95697686 0.42978447]
 [0.24096155 0.63351281 0.89974343]
 [0.28391046 0.03972463 0.21472418]
 [0.32859323 0.70347251 0.77923594]
 [0.65058587 0.0459119  0.640271  ]]


In [19]:
# -1: all
print(mat1.reshape(1, -1).shape)  # -1은 사이즈를 모를경우 자주 사용 
print(mat1.reshape(1, -1))
print("=====")
print(mat1.reshape(-1, 1).shape)
print(mat1.reshape(-1, 1))

(1, 18)
[[0.29649438 0.14200824 0.31950093 0.50969565 0.95697686 0.42978447
  0.24096155 0.63351281 0.89974343 0.28391046 0.03972463 0.21472418
  0.32859323 0.70347251 0.77923594 0.65058587 0.0459119  0.640271  ]]
=====
(18, 1)
[[0.29649438]
 [0.14200824]
 [0.31950093]
 [0.50969565]
 [0.95697686]
 [0.42978447]
 [0.24096155]
 [0.63351281]
 [0.89974343]
 [0.28391046]
 [0.03972463]
 [0.21472418]
 [0.32859323]
 [0.70347251]
 [0.77923594]
 [0.65058587]
 [0.0459119 ]
 [0.640271  ]]


In [20]:
print(mat1.reshape(2, 9).shape)
print(mat1.reshape(9, 2))

(2, 9)
[[0.29649438 0.14200824]
 [0.31950093 0.50969565]
 [0.95697686 0.42978447]
 [0.24096155 0.63351281]
 [0.89974343 0.28391046]
 [0.03972463 0.21472418]
 [0.32859323 0.70347251]
 [0.77923594 0.65058587]
 [0.0459119  0.640271  ]]


In [21]:
mat1.reshape(2,5) #사이즈가 x

ValueError: ignored

In [22]:
# tensor 형태로 나타내기
# tensor란 3차원 이상의 행렬을 표현할때
print(mat1.reshape(3,2,3).shape)
print(mat1.reshape(3,2,3))

(3, 2, 3)
[[[0.29649438 0.14200824 0.31950093]
  [0.50969565 0.95697686 0.42978447]]

 [[0.24096155 0.63351281 0.89974343]
  [0.28391046 0.03972463 0.21472418]]

 [[0.32859323 0.70347251 0.77923594]
  [0.65058587 0.0459119  0.640271  ]]]


matrix 또는 tensor 형태에서도 slicing이 가능합니다!

In [23]:
mat2 = np.arange(24).reshape(-1, 4)
print(mat2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [24]:
mat2[:1,:3]

array([[0, 1, 2]])

In [25]:

mat2[3, 0:2]

array([12, 13])

Math Arithmetic Operations(사칙연산)¶

In [26]:
x = np.array([[1,3,5],[7,9,11],[13,15,17]])
y = np.array([[2,4,6],[8,10,12],[14,16,18]])

print(x)
print(y)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [27]:
x+y

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [28]:
x-y

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [29]:
x*y

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

In [30]:
x/y

array([[0.5       , 0.75      , 0.83333333],
       [0.875     , 0.9       , 0.91666667],
       [0.92857143, 0.9375    , 0.94444444]])

In [31]:
print(x**2)

[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]


In [32]:
print(np.power(x,2))

[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]


In [34]:
np.dot(x,y) #내적

array([[ 96, 114, 132],
       [240, 294, 348],
       [384, 474, 564]])

In [36]:
np.sqrt(x)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479],
       [3.60555128, 3.87298335, 4.12310563]])

In [37]:
# More on matrix operation
z1 = np.array([[2,2,2]])
z2 = np.array([[2,2]])

x * z1

array([[ 2,  6, 10],
       [14, 18, 22],
       [26, 30, 34]])

In [38]:
print(z2.shape)
print(x.shape)
print(x * z2)

(1, 2)
(3, 3)


ValueError: ignored

In [39]:
# 합
print(x)
print(x.sum(axis = 0))
print(x.sum(axis = 1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[21 27 33]
[ 9 27 45]


In [40]:
# 평균
print(x)
print(x.mean(axis = 0))
print(x.mean(axis = 1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[ 7.  9. 11.]
[ 3.  9. 15.]


In [41]:
# 표준편차
print(x)
print(x.std(axis = 0))
print(x.std(axis = 1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[4.89897949 4.89897949 4.89897949]
[1.63299316 1.63299316 1.63299316]


In [42]:
print(x.T) #전치행렬
print(np.dot(x, z1.T))

[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]
[[18]
 [54]
 [90]]


Other operations

In [43]:
xx = np.random.rand(15)
print(xx)

[0.27709027 0.21611408 0.80682141 0.75345543 0.68308114 0.09363051
 0.63472955 0.20618071 0.72115653 0.59454661 0.70222083 0.15852936
 0.09165986 0.81888702 0.08370966]


In [44]:
print(xx)
print(xx.argsort()) # axis를 활용해서 행렬(matrix)에도 적용할 수 있다.
xx.sort()
print(xx)

[0.27709027 0.21611408 0.80682141 0.75345543 0.68308114 0.09363051
 0.63472955 0.20618071 0.72115653 0.59454661 0.70222083 0.15852936
 0.09165986 0.81888702 0.08370966]
[14 12  5 11  7  1  0  9  6  4 10  8  3  2 13]
[0.08370966 0.09165986 0.09363051 0.15852936 0.20618071 0.21611408
 0.27709027 0.59454661 0.63472955 0.68308114 0.70222083 0.72115653
 0.75345543 0.80682141 0.81888702]


pandas

In [45]:
import pandas as pd

In [46]:
pd_series = pd.Series(index = ['a','b','c','d','e'], data=[1,2,3,4,5])
pd_series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [47]:
# Pandas Series의 기초 정보
print('차원:', pd_series.ndim)
print('형태: ', pd_series.shape)
print('총 원소의 수:', pd_series.size)

print('값:', pd_series.values)
print('인덱스:', pd_series.index)

차원: 1
형태:  (5,)
총 원소의 수: 5
값: [1 2 3 4 5]
인덱스: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


In [48]:
# loc(index를 활용하여 access), iloc(integer location)

print(pd_series.loc['a'])
print(pd_series.iloc[0])

print(pd_series.loc[['a','c']])
print(pd_series.iloc[[0,2]])

1
1
a    1
c    3
dtype: int64
a    1
c    3
dtype: int64


In [49]:
pd_series.drop('b') # 원본에서 지우는게 아니다.

a    1
c    3
d    4
e    5
dtype: int64

In [50]:
print(pd_series)
pd_series.drop('b', inplace=True) #원본에 영향을 주려면 inplace = True
print(pd_series)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
c    3
d    4
e    5
dtype: int64


In [51]:
data = {
    'A': np.arange(15),
    'B': np.random.randint(low=0, high=15, size=(15)),
    'C': np.random.rand(15)
}

data_df = pd.DataFrame(data)

In [52]:
data_df

A   B         C
0    0  13  0.239954
1    1   8  0.092205
2    2   4  0.375432
3    3   8  0.053796
4    4   6  0.442368
5    5   3  0.870487
6    6   7  0.108346
7    7   9  0.893472
8    8   9  0.469334
9    9   9  0.734127
10  10  13  0.286669
11  11   4  0.134199
12  12   8  0.770494
13  13   2  0.703381
14  14  11  0.543596

In [53]:
data_df.head()

A   B         C
0  0  13  0.239954
1  1   8  0.092205
2  2   4  0.375432
3  3   8  0.053796
4  4   6  0.442368

In [54]:
data_df.tail()

A   B         C
10  10  13  0.286669
11  11   4  0.134199
12  12   8  0.770494
13  13   2  0.703381
14  14  11  0.543596

In [55]:
data_df.shape

(15, 3)

In [56]:
data_df[1:3]

A  B         C
1  1  8  0.092205
2  2  4  0.375432

In [57]:
data_df.loc[1]['C']

0.09220497378625891

In [59]:
data_df.loc[1][['B','C']]

B    8.000000
C    0.092205
Name: 1, dtype: float64

In [60]:
data_df['D'] = data_df['A'] >= 5
data_df

A   B         C      D
0    0  13  0.239954  False
1    1   8  0.092205  False
2    2   4  0.375432  False
3    3   8  0.053796  False
4    4   6  0.442368  False
5    5   3  0.870487   True
6    6   7  0.108346   True
7    7   9  0.893472   True
8    8   9  0.469334   True
9    9   9  0.734127   True
10  10  13  0.286669   True
11  11   4  0.134199   True
12  12   8  0.770494   True
13  13   2  0.703381   True
14  14  11  0.543596   True

In [61]:
data_df.drop('D', axis=1, inplace=True)

In [62]:
data_df

A   B         C
0    0  13  0.239954
1    1   8  0.092205
2    2   4  0.375432
3    3   8  0.053796
4    4   6  0.442368
5    5   3  0.870487
6    6   7  0.108346
7    7   9  0.893472
8    8   9  0.469334
9    9   9  0.734127
10  10  13  0.286669
11  11   4  0.134199
12  12   8  0.770494
13  13   2  0.703381
14  14  11  0.543596

In [63]:
data_df.sort_index(axis=0, ascending=False)

A   B         C
14  14  11  0.543596
13  13   2  0.703381
12  12   8  0.770494
11  11   4  0.134199
10  10  13  0.286669
9    9   9  0.734127
8    8   9  0.469334
7    7   9  0.893472
6    6   7  0.108346
5    5   3  0.870487
4    4   6  0.442368
3    3   8  0.053796
2    2   4  0.375432
1    1   8  0.092205
0    0  13  0.239954